# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
